[project]
name = "datafusion-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datafusion>=42.0.0",
    "ipykernel>=6.29.5",
]
